image: ubuntu:latest

variables:
  DEBIAN_FRONTEND: noninteractive
  AWS_ACCESS_KEY_ID: "$AWS_ACCESS_KEY_ID"
  AWS_DEFAULT_REGIONL: "$AWS_DEFAULT_REGION"
  AWS_SECRET_ACCESS_KEY: "$AWS_SECRET_ACCESS_KEY"

before_script:
  - apt-get update -y && apt-get install -y curl unzip python3

test:
  script:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - python3 create-account.py $ACCOUNT_OWNER_EMAIL $ACCOUNT_NAME